Makefile
lightstep/recorder.py
lightstep/tracer.py
tests/runtime_test.py

Fixes the following:
- start timestamps were in 1970 (seconds vs microseconds)
- previously ignored the youngest timestamp from the basictracer SpanRecord and hardcoded `now`
- previously ignored log timestamps (which meant they didn't show up in the UI among other things)
- previously imported things like `basictracer` from the local dir rather than via system imports (a la `pip`)
- Makefile referenced removed/renamed files
- a bunch of minor stuff (comments, lint errors, etc)
Does not fix:
- the unittests, though I did run the examples manually and verified correctness manually

address some critical correctness issues

---

lightstep/recorder.py
lightstep/tracer.py
setup.py

... and thus disable the protobuf runtime dependency which can cause problems when there are other versions of the protobuf lib around.
See https://github.com/opentracing/basictracer-python/pull/10.

Allow the user to disable the binary format import

---

lightstep/recorder.py

A few small updates to update the Python client library related to span buffering:
* Re-enqueue reported spans if the report fails
* Drop the newest spans rather than random ones when the buffer is full
* If the buffer is full, early return rather than doing the conversion to the wire format first
* Fix a trivial problem where work was still being done if the client library was disabled

Restore span records on failed reports

---

lightstep/recorder.py
setup.py

Note that this does not offer full key-value logging support; just keeps abreast of BasicTracer changes. The endgame is to support arbitrary keys and values, but that change should come along with the gRPC migration.

Support new basictracer-py LogData

---

examples/trivial/main.py
lightstep/recorder.py
lightstep/util.py
tests/util_test.py

Instead, re-encode them as UTF-8 `str`s.
We also add a last-ditch attempt to not-raise exceptions, though that shouldn't ever be needed.

Don't crash given unicode strings

---

setup.py
tox.ini

As it was, anyone who `pip install`ed this package also got pytest. This isn't the best. Also changed the tests to actually _use_ pytest.

Move pytest from install_requires to tests_require

---

circle.yml
tox.ini

Circle CI ubuntu 14.04 no longer supports any 2.6 python versions.

Remove support for Python 2.6

---

lightstep/recorder.py

Exceptions during worker flush were being swallowed and turned into IndexErrors on the format tuple in `_fine`. This just cleans up a couple things so the exception is surfaced
* logging `args` for format should be splatted when passed
* `traceback.format_exc` first arg is `limit`, not an exception instance

Format error on exception handling

---

circle.yml

According to https://circleci.com/docs/1.0/language-python/ this is the way to test against multiple versions of Python.
The latest commit in `master` breaks because we had forgotten to add a dependency to Python 3.4 ;) 
@frenchfrywpepper @katiabazzi 
PS - Is it possible to automatically run CircleCI for PRs?

Make CircleCI install Python 2.7 and 3.4

---

lightstep/constants.py
lightstep/http_converter.py

As discussed in https://github.com/lightstep/lightstep-tracer-python/issues/56 this PR looks to provide better span timing resolution by providing the `seconds` and `nanos` (fraction of the second) value for the Timestamp proto object. 
I wasn't sure about your contribution policy so I have not updated the VERSION file in the repo, looking at previous commits to master it appears you usually increment this separately in another commit. Happy to include that in this PR if required though.

Calculate and set seconds and nanos for Span's Timestamp proto

---

Makefile
lightstep/crouton/ReportingService.py

When the Satellite is backed by an ELB/ALB/other that transmits 5xx/4xx with some sort of non-Thrift, non-binary message, the Thrift client will attempt to parse this message as binary and fail. This process causes a 10x memory spike on the python process which can lead to erroneous OOM indicators.
This PR also removes the make thrift target, as we are editing generated files in this PR.

Ignore error statuses in Thrift client response path

---

lightstep/http_converter.py
lightstep/util.py
tests/util_test.py

We were missing the nanos component, only
specifying seconds.

Properly set logs tstamp for the http converter.

---

examples/http/context_in_headers.py
lightstep/b3_propagator.py
tests/b3_propagator_test.py

@carlosalberto The example added [here](https://github.com/lightstep/lightstep-tracer-python/pull/80/files#diff-4841a65fd27b3d6d6fe7d259e288b532) is failing because apparently I should use [this](https://github.com/opentracing/basictracer-python/blob/master/basictracer/context.py#L6) instead of [this](https://github.com/opentracing/opentracing-python/blob/master/opentracing/mocktracer/context.py#L26). I am using the latter because it (correct me if I'm wrong, please) more closely matches the OpenTracing specification for the Context, as shown [here](https://opentracing.io/docs/overview/spans/#spancontext) (the latter lacks a `sampled` attribute).
If I should use the former context class, should I use its `sampled` attribute to store the value of the very close `X-B3-Sampled` value?

Add support for B3 headers

---

.gitignore
lightstep/trace_context.py
lightstep/tracer.py
tests/trace-context/conftest.py
tests/trace-context/trace_context_test_service.py
tox.ini

Add support for Trace Context headers

---

lightstep/recorder.py
lightstep/util.py

closes #99
Here is a script that shows how this changes the traceback formatting:
```
import sys
import traceback
try:
try:
raise ValueError("some value")
except ValueError:
raise TypeError("some type")
except Exception:
exc_value, exc_type, exc_tb = sys.exc_info()
print("".join(traceback.format_tb(exc_tb)))
print("=" * 80)
print("".join(traceback.format_exception(None, exc_type, exc_tb)))
print("=" * 80)
print("".join(traceback.format_exception(exc_value, None, exc_tb)))
print("=" * 80)
print("".join(traceback.format_exception(exc_value, exc_type, exc_tb)))
```
Output:
```
$ python foo.py 
File "foo.py", line 9, in <module>
raise TypeError("some type")
================================================================================
Traceback (most recent call last):
File "foo.py", line …
```

format tracebacks with cause

---

lightstep/http_converter.py
lightstep/thrift_converter.py
tests/recorder_test.py

Adding the `lightstep.hostname` tag and re-enabling recorder tests.
Fixes #84

Add lightstep.hostname tag

---

lightstep/recorder.py
lightstep/util.py

This reverts commit 1c945209689be023cd4a7d3634ff3148a8e064a3 introduced in PR https://github.com/lightstep/lightstep-tracer-python/pull/100
This fails with `AttributeError: 'str' object has no attribute '__cause__'` in production for us. I'll look more deeply into why this happened later but for now this should fix the bleeding.

Revert "format tracebacks with cause (#100)"

---

lightstep/recorder.py
lightstep/util.py
tests/recorder_test.py

This PR brings back the change which was originally in #100, added some tests as well as the fix for the issue that came up after some testing of the 4.4.4 release
FYI: @dneuhaeuser-zalando

Re-enable traceback formatting with cause

---

lightstep/b3_propagator.py
tests/b3_propagator_test.py

Cast to string all carrier values

---

CHANGELOG.md
lightstep/http_connection.py
lightstep/recorder.py
tests/recorder_test.py

Do not record non-sampled spans
